/*
 * TeR_CAN.h
 *
 *      Author: Nguyen Nhan
 *
 * ████████╗███████╗██████╗          ██████╗ █████╗ ███╗   ██╗
 * ╚══██╔══╝██╔════╝██╔══██╗        ██╔════╝██╔══██╗████╗  ██║
 *    ██║   █████╗  ██████╔╝        ██║     ███████║██╔██╗ ██║
 *    ██║   ██╔══╝  ██╔══██╗        ██║     ██╔══██║██║╚██╗██║
 *    ██║   ███████╗██║  ██║███████╗╚██████╗██║  ██║██║ ╚████║
 *    ╚═╝   ╚══════╝╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═══╝
 */

/*  This file aims to store the decoding and sending functions
 *  of all messages from a board, includes as libraries those
 *  autogenerated using cantools and offers an interface to the micro with two
 *  Functions:
 *  - decodeMSG -> Decodes the relevant structures
 *  - sendCAN -> Sends the relevant messages (This will not depend on the state, since the inverters will always be at 0)
 *	- cmd() -> Function that is called when the command message is received so that each board interprets it as appropriate
 *
 *  All CAN memory structures are created here
 */

#ifndef INC_TER_CAN_H_
#define INC_TER_CAN_H_

#include "stm32f4xx.h"  // For bare-metal CAN and TIM registers
// DBCS
#include "ter.h"  // For TER DBC structures
#include "inverter.h"  // For inverter DBC structures
#include "hvbms.h"  // For HVBMS DBC structures
// Utilities
#include "TeR_SCS.h"  // For logging SCS
#include "TeR_COMMAND.h"  // For command calls

/* --------------------- Vehicle Data Structures ----------------- */
// TER.dbc
struct TeR_t {
	// Own
	struct ter_ter_status_t status;  // TER status
	struct ter_dynamic_config_t dynamicConfig;  // Dynamic configuration
	struct ter_wheel_info_t wheelInfo;  // Wheel information
	struct ter_inverter_info_t invInfo;  // Inverter information

	// Sent
	struct ter_command_t cmd;  // Command
	struct ter_trq_req_right_t trqReqRight;  // Right torque request
	struct ter_trq_req_left_t trqReqLeft;  // Left torque request

	// Received
	struct ter_apps_t apps;  // APPS
	struct ter_bpps_t bpps;  // BPPS
	struct ter_steer_t steer;  // Steering
	struct ter_front_v_t speed;  // Front velocity
	struct ter_ang_rate_t angRate;  // Angular rate
	struct ter_lv_status_t lvbms;  // LV status

	// Inverter.dbc
	// Sent
	struct inverter_app_req_right_t appReqRight;  // Right app request
	struct inverter_app_req_left_t appReqLeft;  // Left app request

	// Received
	struct inverter_emcu_state_2_right_t appStateRight;  // Right inverter state
	struct inverter_emcu_state_2_left_t appStateLeft;  // Left inverter state

	struct inverter_emcu_state_3_right_t dqErpmRight;  // Right current D,Q and erpm
	struct inverter_emcu_state_3_left_t dqErpmLeft;  // Left current D,Q and erpm

	struct inverter_emcu_state_4_right_t tempsRight;  // Right inverter temperatures
	struct inverter_emcu_state_4_left_t tempsLeft;  // Left inverter temperatures

	struct inverter_emcu_state_9_right_t trqEstRight;  // Right torque estimation
	struct inverter_emcu_state_9_left_t trqEstLeft;  // Left torque estimation

	struct inverter_emcu_state_7_right_t demRight;  // Right DEM
	struct inverter_emcu_state_7_left_t demLeft;  // Left DEM

	// HVBMS.dbc
	// Sent
	struct hvbms_bms_rx_ctrl_1_t BmsAppReq;  // BMS state command
	// Received
	struct hvbms_bms_tx_state_3_t BmsAppState;  // BMS state
};

// General working struct
extern struct TeR_t TeR;  // Exposes TeR data to other files

// Expose CAN peripherals to other modules
extern CAN_TypeDef *mainCAN;
extern CAN_TypeDef *invCAN;

/* ---------------------------------------------------------------------- */

// Function prototypes
uint8_t initCAN(CAN_TypeDef *invCan, CAN_TypeDef *mainCan,
		TIM_TypeDef *hInvTIM, TIM_TypeDef *hMainTIM);  // Initializes CAN and timers
void configFilter(CAN_TypeDef *invCan, CAN_TypeDef *mainCan);  // Configures filters
void decodeMsg(CAN_TypeDef *hcan);  // Decodes message according to DBC
void sendInvCAN(TIM_TypeDef *htim);  // Callback function for sending on inverter CAN
void sendMainCAN(TIM_TypeDef *htim);  // Callback function for sending on main CAN

#endif /* INC_TER_CAN_H_ */